version: '3.3'
services:
    minions:
        build:
            context: ../MAAM/
            dockerfile: Dockerfile
        ports:
            - '8080:80'
        container_name: minions_maam
        restart: always
        volumes:
            - '/nfs/docker/volumes/minions:/app/_data'
        image: home-server:5000/mrh4287/minions_maam
        